### ISSUE TITLE
Test fixtures are ignored by deftest

### ISSUE THREAD

**Issue by bsteuber** [bhauman/devcards#104]
Hi - and thanks for the great work with figwheel and devcards :D

The following example breaks in the devcards view, but works fine when using cljs.test/run-tests instead.
If you provide some help on how to implement it I could try providing a patch myself.

```
(ns fixture.example
  (:require [cljs.test     :refer-macros [use-fixtures is]]
            [devcards.core :refer-macros [deftest]]))

(def state (atom nil))

(use-fixtures :each
  {:before (fn []
             (reset! state :foo))})

(deftest fixtures
  (is (= :foo @state)))
```

**Comment by bhauman** [comment]
This is true and unfortunately, fixing it is non trivial.  It has to do with a subtle miss-match asynchrony of the the live coding process and the design of fixtures in cljs-test.  In order to catch errors for async tests in Devcards things get a bit tricky.  

This was an attempt that ignored all the edge cases:
https://github.com/bhauman/devcards/pull/76

**Comment by bsteuber** [comment]
I see, it looks really complicated indeed - that's a pity..

**Comment by sp3ctum** [comment]
This doesn't really bother me right now - but for the record: is there some workaround?

**Comment by bhauman** [comment]
I highly recommend that folks use https://github.com/bhauman/cljs-test-display
