### ISSUE TITLE
Documentation: Showing multiple source files' cards in the devcards interface

### ISSUE THREAD

**Issue by mathpunk** [bhauman/devcards#66]
This seems so silly but I can't figure out what I need to change. I've got a project, and I'm making cards in `foo.core` and they show up when I run `lein figwheel` and everything is kittens and rainbows. But, if I make a `foo.baz` source file, it is not available as one of the visual namespaces to choose from. I see this pattern all over in the examples, but I haven't found what's different about my project. 

Other than the cards I've added to `foo.core`, it's the bare bones result of `lein new devcards foo`.

**Comment by bhauman** [comment]
You need to require 'foo.baz from 'foo.core right?  The namespace has to be part of the program.

**Comment by mathpunk** [comment]
`lein new devcards foo` is for making the devcards not the app that you're using devcards to develop! Am I getting that right? In that case, when you're using the cards, how do you keep a `something.core` that represents an application itself? (I figure I'm asking a "more than one way to do it" question, but what's simple?)

**Comment by bhauman** [comment]
So I normally start with the cards inline with my code.  And then I start moving them to a devcards only build.

Either way you need to configure a devcards build and a build without devcards.

**Comment by drusellers** [comment]
@mathpunk you can see an example of multiple cards showing here: https://github.com/bhauman/devcards/blob/master/example_src/devdemos/start_ui.cljs - but yeah, what ever file is the 'main' file just needs to require in the other ones.

**Comment by Vaguery** [comment]
I have to say I'm having the same sort of trouble working through the architecture of an app that

1. has several files of literate `devcards` files as documentation & narrative & examples, which should be rendered in production
2. has a single "`devcards` index" page, which builds an index of all those `devcards` files, as we see in [the demo menu](https://github.com/bhauman/devcards/tree/master/example_src) here
3. has a "main" interface page, rendered in production (of course)
4. _also_ has some "working it out" dev-only `devcards` files, where I'm actually doing the dev work and other exploratory stuff that probably shouldn't go into the production release

I think you'll need to do a bit more hand-holding, since frankly a lot of us will probably be coming to the table while we're learning all of Clojurescript, idiomatic cljs web architecture, compiler profiles, and all the rest at once. :)

So I guess some practical questions:

- Is there a function in `devcards.core` that builds the nested tree of individual pages for individual `devcards` files? Is that what `devcards.core/start_ui` is doing?
- Is there a way to flag some `devcards` files so they aren't included? Or is just a matter of including them in the `start-ui` view file the only way to approach this? Should I therefore have one **production** build target that only includes my "good" `devcard` files, and another **dev** target that includes all of them I'm working with?

In under a day I've easily reached the point where I want to split one monolithic file out into specific components. But not understanding how to quickly build an index (ideally dynamically) makes this hard to do.

**Comment by Vaguery** [comment]
OK, I seem to have stumbled onto what I was asking after:

1. construct a file `my-project/env/dev/cljs/start_ui.cljs` something like this:
  
  ~~~cljs
  (ns my-project.start-ui
  (:require
   [devcards.core]
   [my-project.learning-about-devcards]  ;; one devcards namespace I want to include
   [my-project.pareto-gp-testing-cards]  ;; another devcards namespace I want to include
  ;; ...
   ))

(defn ^:export main []
  (devcards.core/start-devcard-ui!))
  ~~~
2. modify `my-project/project.clj` to include a `:cljsbuild {:builds {:devcards ...` with config something like

  ~~~cljs
:devcards
            {:source-paths ["src/cljs" "src/cljc" "env/dev/cljs"]
             :figwheel {:devcards true}
             :compiler {:main "my-project.start-ui"
                        :externs ["externs.js"]
                        :asset-path "js/devcards_out"
                        :output-to "target/cljsbuild/public/js/app_devcards.js"
                        :output-dir "target/cljsbuild/public/js/devcards_out"
                        :source-map-timestamp true
                        :optimizations :none
                        :pretty-print true}}
  ~~~

As a result, when I invoke `lein figwheel devcards` and navigate to `localhost:3449/cards` I now see the single-page app which includes a branch for every `devcards` namespace I included in step 1. 

I note the comment that `(devcards.core/start-devcard-ui!)` is "experimental", but to be honest I think this should quickly become a core facet of the workflow. I write a lot of tests, and I want an _awful_ lot of docs. In fact, I imagine almost _anybody_ who ever writes tests or docs will find this useful. Literate, exploratory, even test-driven work can be hugely helpful. But when you do _enough_ of it, you really need this extra aspect of organizing it better.

Can you or one of us promote this "experimental" `(devcards.core/start-devcard-ui!)` call to full feature status? It's awesome to the point of being necessary.

**Comment by dmitriid** [comment]
This is what happened in my case:

- in file `my-ns.core` `(:require [my-ns.components.core :as components])`
- in file `my-ns.components.core` I have 

```clojure
(:require-macros
    [devcards.core :as dc :refer [defcard defcard-doc]])
```

And that's it. When I run the page, devcards appear at the top of the page. However, they are not collapsed, it's a list of all namespaces that contain devcards
